### PR TITLE
add Hack fonts

### PR DESCRIPTION
**Pull request by chrissimpkins**
PR includes the Hack Regular, Oblique, Bold, and BoldOblique ttf binaries (Regular set is patched with Powerline glyphs by default in my releases) and supporting documentation in the style used in this repository.   I attempted a screenshot using the same code that you display for the other typefaces and included the image in the Hack subdirectory.  

If you accept the PR, the `samples/All.md` and `samples/Hack.md` files will need to be modified with the screenshot image link.

Let me know if there is anything else that you need.

### CODE REVIEW

**Comment by Lokaltog** [comment]
Thanks a lot! The fonts will have to be renamed in a similar fashion to the other fonts using the same license - the SIL font license doesn't permit distributing any modified versions containing the original name. Renaming the font to "Shack" or "Hackerline" or something like that should be sufficient. The directory name etc. can remain the same, only the font name in the font files themselves need to be changed.

**Comment by chrissimpkins** [comment]
I included the powerline glyphs by default in my release of the font (I am the developer).  They haven't been modified from the way that I released them under the reserved name Hack.  These are my release binaries that I would like to include in this repository for your users.  

We should be OK with licensing.

**Comment by Lokaltog** [comment]
Haha, sorry about that, I didn't realize. Just wanted to be sure about the licensing and naming since it's been an issue with the other fonts in the past. Thanks again!

**Comment by chrissimpkins** [comment]
It's an important issue and the right thing to do! No worries at all.  Thanks for including them.  Please let me know if any users have issues with them.  I am happy to address the issues for them.

**Pull request merged**
