### PR TITLE
Adding Go-Mono

### PR DESCRIPTION
**Pull request by JesseObrien**
Adding the new Go-Mono font. 

https://blog.golang.org/go-fonts

### CODE REVIEW

**Comment by macat** [comment]
+1

**Comment by AnwarShah** [comment]
Can you add the other variants like Bold and italics?

**Comment by AnwarShah** [comment]
I added all four variant later with this commit https://github.com/powerline/fonts/pull/204/commits

**Comment by JuanCabre** [comment]
Merge this please :D

**Comment by mwhooker** [comment]
here's what my vanilla airline looks like with this font. using vim in iterm2 on osx

screen shot 2017-02-13 at 1 38 57 pm

I'm not sure the branch glyph looks correct, but works pretty well otherwise

**Comment by antonpaisov** [comment]
why only Regular?

**Comment by ZyX-I** [comment]
Closed as #204 was merged.

**Pull request closed without merging**
