### PR TITLE
Spacemono

### PR DESCRIPTION
**Pull request by DoctorOkay**
I added and patched the font SpaceMono. A clean mono font designed by Colophon.

### CODE REVIEW

**Comment by ZyX-I** [comment]
License needs to be `LICENSE.txt`. And do not remove trailing whitespace from README.

**Comment by DoctorOkay** [comment]
I made those changes. Let me know if it looks good

**Comment by ZyX-I** [comment]
The latest change does not readd trailing whitespace to README. I think you have it removal automatic, disable.

**Comment by DoctorOkay** [comment]
With any luck that fixed it. Atom had a setting to automatically remove trailing whitespace that I didn't know about. I turned that off, re-copied the README from master, and re-saved the file

**Pull request merged**
