### PR TITLE
add windows install script

### PR DESCRIPTION
**Pull request by ehartford**
add windows install script

### CODE REVIEW

**Comment by dawikur** [comment]
:+1: 
I would also find bat script useful :smiley:

**Comment by ehartford** [comment]
install.bat:
    Powershell.exe -executionpolicy remotesigned -File install.ps1

**Comment by dawikur** [comment]
I was hoping it would be merged into repository so I wouldn't need too modify my setup scripts.  Anyway, thanks :smiley:

**Comment by wby238** [comment]
@ehartford What happens ?

```powershell
F:\git\fonts>Powershell.exe -executionpolicy remotesigned -File install.ps1
命名参数后缺少“=”运算符。(lack "=")
所在位置 F:\git\fonts\install.ps1:18 字符: 38
+ [CmdletBinding(SupportsShouldProcess) <<<< ]
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEqualsInNamedArgument
```

**Pull request merged**
