### PR TITLE
Avoid hard-coded bash path in sha-bang

### PR DESCRIPTION
**Pull request by iblis17**
Make it work on other unix (e.g. bsd family). :smile:

### CODE REVIEW

**Comment by xvilo** [comment]
When is this going to be merged? I haven't been in luck to install this on freebsd.... 

img

**Comment by WuglyakBolgoink** [comment]
@iblis17 can you fix merge conflicts?

**Review by WuglyakBolgoink — APPROVED** [review]
more info here:
https://stackoverflow.com/a/16365367

**Comment by iblis17** [comment]
ah, I think `/bin/sh` in master is fine for every system?

**Pull request closed without merging**
