### PR TITLE
only try fc-cache reset on linux

### PR DESCRIPTION
**Pull request by CarlQLange**
fc-cache doesn't exist on osx :)

### CODE REVIEW

**Comment by Lokaltog** [comment]
I'm pretty sure `if [[ -n `which fc-cache` ]]` checks if `fc-cache` exists in `$PATH`, so this command shouldn't run if `fc-cache` is unavailable.

**Comment by CarlQLange** [comment]
fyi it did actually try to run fc-cache on my machine, hence the need for this patch, as the script bombed out without it.

    if [[-n `which fc-cache ]]

actually checks if the output of `which fc-cache` and tests if it's a null string or not. At least on my machine, if `which` can't find `fc-cache`, it says 'fc-cache not found', not an empty string. A better test is something like:

    if command -v fc-cache 2>/dev/null; then fc-cache -f $font_dir; fi

[Here's more info about why you should avoid `which` in this script](https://stackoverflow.com/a/677212)

And here's a screenshot of the current if not working:

screen shot 2015-11-18 at 08 33 49

**Comment by Lokaltog** [comment]
Allright, that makes sense. On Linux the output of `which` is empty if the command doesn't exist, I didn't realize this behavior isn't consistent across systems. I think that instead of testing the `uname` output we should fix the issue with using `which` so it works consistently across systems.

I agree with the `if command...` solution you posted, if you could update the PR I'll merge it.

**Comment by CarlQLange** [comment]
OK, updated. You might want to make sure it works the same way on your system. It works fine for me now. :)

**Comment by Lokaltog** [comment]
Works like a charm, thanks a lot!

**Pull request merged**
